"""Centralised configuration: all file paths and application constants."""

from pathlib import Path

# Project root: three levels above this file (src/scoring_bank/config.py)
ROOT = Path(__file__).resolve().parents[2]

# Data
DATA_PATH = ROOT / "data" / "data_api.csv"

# Pre-computed CSVs for the dashboard (generated by notebook 02)
INTERPRETABLE_CSV = ROOT / "data" / "df_interprete.csv"
INTERPRETABLE_NO_UNIT_CSV = ROOT / "data" / "df_interp_sans_unite.csv"
GROUP_CSV = ROOT / "data" / "df_group.csv"
NN_CSV = ROOT / "data" / "df_nn.csv"
GENRE_CSV = ROOT / "data" / "genre.csv"
INCOME_CSV = ROOT / "data" / "income.csv"
EDUCATION_CSV = ROOT / "data" / "education_type.csv"
ORGANIZATION_CSV = ROOT / "data" / "organization_type.csv"
FAMILY_CSV = ROOT / "data" / "family.csv"

# Models
MODELS_DIR = ROOT / "models"
LGBM_MODEL_PATH = MODELS_DIR / "LightGBMModel.pkl"
NN_MODEL_PATH = MODELS_DIR / "NearestNeighborsModel.pkl"
SCALER_PATH = MODELS_DIR / "StandardScaler.pkl"

# Features used by both the scorer and the nearest-neighbor lookup
INTERPRETABLE_FEATURES: list[str] = [
    "SK_ID_CURR",
    "PAYMENT_RATE",
    "AMT_ANNUITY",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "ANNUITY_INCOME_PERC",
]

# Default decision threshold for loan approval
DEFAULT_THRESHOLD: float = 0.50

# Client ID range present in data_api.csv
CLIENT_ID_MIN: int = 100002
CLIENT_ID_MAX: int = 112188
